name: Trigger auto deployment for demohub-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demohub-backend-AutoDeployTrigger-60620d95-bf6f-4702-9706-7724fa29f9ef.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEMOHUBBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOHUBBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOHUBBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile
          registryUrl: demohubregistry.azurecr.io
          registryUsername: ${{ secrets.DEMOHUBBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOHUBBACKEND_REGISTRY_PASSWORD }}
          containerAppName: demohub-backend
          resourceGroup: demohub-rg
          imageToBuild: demohubregistry.azurecr.io/demohub-backend:${{ github.sha }}
          targetPort: 4000


